# Generated by Django 4.2.4 on 2023-08-25 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flagging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(max_length=11)),
                ('businesses', models.ManyToManyField(related_name='users', to='flagging.business')),
            ],
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
    ]
