# Generated by Django 4.2.4 on 2023-08-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flagging', '0003_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='businesses',
        ),
        migrations.AddField(
            model_name='flag',
            name='businesses',
            field=models.ManyToManyField(related_name='users', to='flagging.business'),
        ),
    ]
